### ISSUE TITLE
[etc] 프로젝트 하면서 배운 지식들 정리

### ISSUE THREAD

**Issue by rigood** [rigood/pokemon#4]
**1. 첫 글자 대문자로 표시**
```css
span::first-letter{
  text-transform: uppercase;
}
```

<br>

**2. 배경 이미지 여러개 사용**
```css
background-image: url(${img1}), url(${img2)});
```

<br>

**3. CSS background 속성 축약형**
```
background: color image repeat position / size attachment
```
```css
background: ${(props) => props.theme.colors.white} url(${Pokeball}) no-repeat center top / 105%;
// 색상 이미지 반복 위치 / 크기
```

<br>

**4. 이미지 import 방식**
   - 저장폴더
      - public 폴더: 원본파일이 build 폴더에 복사됨, 경로가 잘못된 경우 404 에러 발생, 여러장의 이미지를 동적으로 참고해야 할 때 사용
      - src 폴더: Webpack에 의해 압축됨, 경로가 잘못된 경우 컴파일 에러 발생, 크기가 작은 이미지는 path 대신 data URL 반환

<br>

   - **public 폴더**에 저장
     - html 문서: `%PUBLIC_URL%` 사용
     - JSX 파일: `process.env.PUBLIC_URL` 사용
```html
// html 문서 (파비콘 설정)
<link rel="shortcut icon" href="%PUBLIC_URL%/assets/icons/icon.png" />
```
```js
// JSX 파일
<img src={process.env.PUBLIC_URL + `/assets/badges/${type.name}.png`} />
```

<br>

   - **src 폴더**에 저장
     - 상단에 이미지 import한 후 변수로 사용
```js
// styled-components로 css 설정
import Pattern from "../assets/pattern.png";

const Wrapper = styled.div`
background-image: url(${Pattern}), url(${Pokeball});

// jsx 파일에 이미지 넣기
import 이미지변수 from 경로;
<img src={이미지변수} />
```

<br>

**5. 스크롤바 꾸미기**
![image](https://github.com/rigood/pokemon/assets/105968419/85c961ec-347e-4ad7-bf8e-cbbdc79351f7)
```css
  &::-webkit-scrollbar {
    width: 20px;
  }

  &::-webkit-scrollbar-thumb {
    background-color: ${(props) => props.theme.colors.secondary};
    border-radius: 10px;
    border: 7px solid white;
  }

  &::-webkit-scrollbar-track {
    background-color: transparent;
  }
```
